spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: username
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

kafka:
  bootstrap-servers: kafka:9092
  topic: user-events
  consumer-groupId: notification-user-group
  auto-offset: earliest
