spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/mydatabase
    username: ${DB_USERNAME:myuser}
    password: ${DB_PASSWORD:secret}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties.hibernate:
      use_sql_comments: true
      format_sql: true

kafka:
  bootstrap-servers: kafka:9092
  topic: user-events

resilience4j:
  retry:
    configs:
      kafka-retry:
        max-attempts: 5
        wait-duration: 4s
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
    instances:
      userEventsProducer:
        base-config: kafka-retry

  circuitbreaker:
    configs:
      kafka-cb:
        failure-rate-threshold: 50
        slow-call-rate-threshold: 70
        slow-call-duration-threshold: 5s
        sliding-window-size: 20
        minimum-number-of-calls: 5
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3
    instances:
      userEventsProducer:
        base-config: kafka-cb
