server:
  port: 8761

spring:
  application:
    name: service-discovery
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}"
  cloud:
    config:
      fail-fast: true
      retry:
        initial-interval: 1000
        max-attempts: 6
        max-interval: 2000
  output:
    ansi:
      enabled: always
